services:
  app:
    build: .
    environment:
      - EVENTS_STORAGE=/data/timestamp
      - LOGS_LOCATION=/data/riscv_lab.log
    volumes:
      - type: bind
        source: secrets.json
        target: /secrets.json
      - type: volume
        source: data 
        target: /data
volumes:
  data:
