name: Test kernel workflow
on:
  workflow_dispatch:
    inputs:
      kernel-url:
        description: 'Compiled kernel image url'
        required: true
        type: string
      selftests-url:
        description: 'Compiled selftests url'
        required: true
        type: string
      build-id:
        description: 'Build id'
        required: true
        type: string
jobs:
  run-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y \
            opensbi \
            curl \
            qemu-system-riscv64 \
            qemu-utils \
            kmod \
            tar \
            unzip
      - name: Download Debian image
        run: ./tests_runner/download_image.sh
      - name: Add selftests to image
        run: sudo ./tests_runner/copy_selftests.sh "${{ inputs.selftests-url }}" /tmp/dqib_riscv64-virt/image.qcow2
      - name: Start up QEMU
        run: ./tests_runner/run_qemu.sh "${{ inputs.kernel-url }}" /tmp/dqib_riscv64-virt/image.qcow2 /tmp/dqib_riscv64-virt/initrd "${{ inputs.build-id }}"
      - name: Run tests
        run: ./tests_runner/run_tests.sh /tmp/dqib_riscv64-virt/ssh_user_rsa_key "${{ inputs.build-id }}"
      - name: Print results
        run: ./tests_runner/print_tests_results.sh "${{ inputs.build-id }}"

